### ISSUE TITLE
Created issue

### ISSUE THREAD

**Issue by modem7** [imjohnbo/extract-issue-template-fields#3]
Heya, 

Is there a way to use this to extract the values from a created issue from a template? 

e.g. User uses template to create issue 1 with body "test", extract the value "test" and use it.

**Comment by imjohnbo** [comment]
Heyo,

This action is for the template side of issue creation... but you might find https://github.com/imjohnbo/issue-bot helpful 🤖. It [outputs](https://github.com/imjohnbo/issue-bot/blob/78e781a6daa38e271e4def56fb124caaa9fe59c2/.github/workflows/publish.yml#L104-L108) the current and previous issue number so you can do things like extract the `body` value in subsequent steps, e.g. using [`gh api`](https://cli.github.com/manual/gh_api) you could use this [REST endpoint](https://docs.github.com/en/rest/reference/issues#get-an-issue).

**Comment by modem7** [comment]
Good shout, thank you!
