### ISSUE TITLE
Update to Node.js 16 as Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by krukow** [imjohnbo/extract-issue-template-fields#5]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: imjohnbo/extract-issue-template-fields@52e76900691b6fcfe3012cf7aa645863fe0cb497

Results in deprecation warnings in user workflows

**Comment by imjohnbo** [comment]
Sorry for the delay. Thanks to @seigel, this should be solved by https://github.com/imjohnbo/extract-issue-template-fields/pull/6. 🎉
