### ISSUE TITLE
Still getting "`set-output` command is deprecated" error when running this action

### ISSUE THREAD

**Issue by slgraff** [imjohnbo/extract-issue-template-fields#7]
I have an action that uses the latest version of imjohnbo/extract-issue-template-fields. When running I always see the following error repeated four times:

>Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I did see the previous issues where this was believed to be fixed. I'm an Actions newbie so maybe I'm just not understanding the cause of this problem?

I've created a sanitized version of the workflow and the issue template in the following public repository:

https://github.com/slgraff/1-on-1-sample-action/

**Comment by imjohnbo** [comment]
Thanks @slgraff! I think I just needed to cut a new release to account for @seigel's change in https://github.com/imjohnbo/extract-issue-template-fields/pull/6.

Could you try [`v1.0.2`](https://github.com/imjohnbo/extract-issue-template-fields/releases/tag/v1.0.2)?

Read more here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by slgraff** [comment]
That eliminated all but one of the warnings. I still get one:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: imjohnbo/extract-issue-template-fields@v1.0.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by imjohnbo** [comment]
Right you are! I believe [`v1.0.3`](https://github.com/imjohnbo/extract-issue-template-fields/releases/tag/v1.0.3) should do the trick. Please let me know if this isn't the case. 🙏

**Comment by slgraff** [comment]
That did it! Thanks for your help!
